### ISSUE TITLE
Make method public in ReaderFactory

### ISSUE THREAD

**Issue by gagauz** [i-net-software/jlessc#25]
Please make method *_create *_public (or protected)  in *_ReaderFactory *_. It's impossible to override it right now.

**Comment by mweirauch** [comment]
Nice one! I just discovered jlessc last evening and was about to ask the same. @Horcrux7 can you give a rough schedule estimate about the next release so that ReaderFactory derivatives don't have to be placed in `com.inet.lib.less` for the time being?

**Comment by Horcrux7** [comment]
@mweirauch For the most users the class ReaderFactory should not of hinteresst. Because there was just a release the next release will take some month. If it important for you then you can:
- use the source files to add to your project
- use a snapshot repository https://oss.sonatype.org/content/repositories/snapshots/
- or download a snapshot jar file https://oss.sonatype.org/content/repositories/snapshots/de/inetsoftware/jlessc/1.5-SNAPSHOT/jlessc-1.5-20160330.165938-1.jar

**Comment by mweirauch** [comment]
Thanks for your reply @Horcrux7 . I might need to normalize some paths with pseudo "webjars!" scheme paths. That's why the non package private method would be useful.
