### ISSUE TITLE
Specify Less.js source versions supported

### ISSUE THREAD

**Issue by jtfennell** [i-net-software/jlessc#43]
It would be helpful if the README indicated the features supported by this compiler, or better yet, the version of the reference implementation the compiler is synced with. It is difficult to tell whether it will work with the less version my project currently uses.

**Comment by Horcrux7** [comment]
There is no matching to a specific Less version. That this is not possible to answer. Because the less project does not have a documentation of 100% of all features and the version in which it was implemented.

To see if it is compatible you can only compare the output of both tools and if you find a significant difference to open a bug/feature request.

If I must answer this question then JLessc should be mostly compatible with version 2.x
