### ISSUE TITLE
Fails to process protocol-relative URL in @import CSS at-rule

### ISSUE THREAD

**Issue by aurelien-minvielle** [i-net-software/jlessc#65]
Hello,

Protocol-relative URLs fail to be parsed inside an `@import` CSS at-rule.
This is frequently used to import fonts from a CDN.

Here a test to reproduce the issue:
```
    @Test
    void shouldSupportSchemeRelatedUrls() {
        String less = "@import url(//fonts.googleapis.com/css?family=Open+Sans);";

        String result = Less.compile(null, less, false);

        assertThat(result).isEqualToIgnoringWhitespace("@import url(//fonts.googleapis.com/css?family=Open+Sans);");
    }
```

Actual behaviour: raises a `java.net.MalformedURLException`.

```
java.net.MalformedURLException: no protocol: //fonts.googleapis.com/css?family=Open+Sans
	 on line 1, column 57
com.inet.lib.less.LessException: java.net.MalformedURLException: no protocol: //fonts.googleapis.com/css?family=Open+Sans
	 on line 1, column 57
	at com.inet.lib.less.LessParser.importFile(LessParser.java:600)
	at com.inet.lib.less.LessParser.variable(LessParser.java:417)
	at com.inet.lib.less.LessParser.parseSemicolon(LessParser.java:228)
	at com.inet.lib.less.LessParser.parse(LessParser.java:158)
	at com.inet.lib.less.LessParser.parse(LessParser.java:122)
	at com.inet.lib.less.Less.compile(Less.java:129)
	at com.inet.lib.less.Less.compile(Less.java:88)
	at com.inet.lib.less.Less.compile(Less.java:68)
```

**Comment by Horcrux7** [comment]
It look like that you does not want process the URL. Then you can option`(css)`. Then your code should look like:

`String less = "@import (css) url(//fonts.googleapis.com/css?family=Open+Sans);";
`

**Comment by aurelien-minvielle** [comment]
Thanks for the workaround. Unfortunately, this is does not come from my own static stylesheet. These protocol-relative URLs come from my end-users custom LESS styles, that I'm trying to compile *at runtime* with jlessc and cannot change.

As this is a valid CSS syntax, isn't it expected to be valid LESS as well ?

**Comment by Horcrux7** [comment]
> As this is a valid CSS syntax, isn't it expected to be valid LESS as well ?

Please try it self out. If I use it with lessc then it resolve the URL and inline it as less code. But the URL contains CSS code. The result is not the expected output.

lessc use also not a relative protocol. It seems to use a default protocol of HTTP.

The main question is what do you want as output? Your test in this issue is wrong. Depending of the expected output you or your customer must modify the less code. Or you must change your test code. For example if the base URL ends with `css` the behavior is different.

**Comment by aurelien-minvielle** [comment]
Oh, sorry, ok : I was not aware lessc fetches and inline the target URL.
This is new from lessc 3.0.0.
Previous lessc behaviour was to leave this @import at-rule as-is without any modifications. (see https://ecomfe.github.io/est/fiddle/#version=2.7.3&code=QGltcG9ydCB1cmwoLy9mb250cy5nb29nbGVhcGlzLmNvbS9jc3M%2FZmFtaWx5PU9wZW4rU2Fucyk7Cg%3D%3D)

As I'm migrating from styles currently compiled with lessc 1.7, I guess both behaviours would work for me: either leave the @import as-it or fetch it and inline it.
My main concern is the raised exception that stops and fails the whole stylesheet compilation.

**Comment by Horcrux7** [comment]
I does not know how your link compile this internally. It look like it use a base URL of its own side. The problem is that if you does not set any options then lessc will guess what you want. Then small changes result in a different behavior. The behavior of your sample site is also different from the lesscss console version.

For example if the URL ends with css then it will work:
`
less = "@import url(//fonts.googleapis.com/css);";
`

Another solution is to set a base URL. If you work with relative URLs then this is recommended. This will also work:
`
String result2 = Less.compile( new URL( "https://github.com/" ), less, true );
`

But my fix will also solve the problem. But you see that lesscss has change it default behavior. That I suggest to set an option for wanted behavior.
